# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

# Capacitor pods
def capacitor_pods
  pod 'Capacitor', :path => '../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../node_modules/@capacitor/ios'
end

target 'Quantedits' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Capacitor
  capacitor_pods

  # Google ML Kit Face Detection (on-device)
  pod 'GoogleMLKit/FaceDetection', '~> 7.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
    end
  end
end
